// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table CustomerEvents (eventId:string, eventTime:string, orderId:string, status:string, amount:real, quantity:long, paymentMethod:string, currency:string, customerId:string, productId:string, merchantId:string, customerSatisfaction:long, source:string, schemaVersion:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
